import { FactoryBlueprint } from '../types/politics';

export const TAKHTA_FACTORY_CATALOG: Record<string, FactoryBlueprint> = {
  'Kilang Berlian': {
    id: 'f_diamond',
    name: 'Kilang Berlian',
    icon: '💎',
    resourceId: 'BERLIAN',
    category: 'Galian Permata',
    buildCostRM: 50000,
    baseOutput: 10,
    outputName: 'Karat Berlian',
    desc: 'Diperlukan untuk teknologi satelit dan pesanan ketenteraan.',
    minDevLevel: 6,
  },
  'Kilang Kulit': {
    id: 'f_leather',
    name: 'Kilang Kulit',
    icon: '🐂',
    resourceId: 'KULIT',
    category: 'Ternakan & Tekstil',
    buildCostRM: 21000,
    baseOutput: 40,
    outputName: 'Gulung Kulit',
    desc: 'Bahan asas pembuatan seragam tentera dan perisai ringan.',
    minDevLevel: 2,
  },
  'Lombong Emas': {
    id: 'f_gold',
    name: 'Lombong Emas',
    icon: '🟡',
    resourceId: 'EMAS',
    category: 'Logam Bernilai',
    buildCostRM: 45000,
    baseOutput: 25,
    outputName: 'Jongkong Emas',
    desc: 'Mata wang simpanan rizab negara dan urusan bursa saham.',
    minDevLevel: 4,
  },
  'Loji Minyak Mentah': {
    id: 'f_crude_oil',
    name: 'Loji Minyak Mentah',
    icon: '🛢',
    resourceId: 'MINYAK',
    category: 'Tenaga Fosil',
    buildCostRM: 35000,
    baseOutput: 60,
    outputName: 'Tong Minyak Mentah',
    desc: 'Bahan mentah pelincir industri perkapalan dan loji elektrik.',
    minDevLevel: 4,
  },
  'Kilang Penapisan Minyak': {
    id: 'f_refined_oil',
    name: 'Kilang Penapisan Minyak',
    icon: '⛽',
    resourceId: 'MINYAK_DITAPIS',
    category: 'Petrokimia',
    buildCostRM: 50000,
    baseOutput: 30,
    outputName: 'Bahan Api Jet',
    desc: 'Bahan bakar jentera berat, peluru berpandu, dan logistik maritim.',
    minDevLevel: 5,
  },
  'Kilang NTE': {
    id: 'f_nte',
    name: 'Kilang NTE',
    icon: '🔋',
    resourceId: 'NTE',
    category: 'Teknologi Tinggi',
    buildCostRM: 25000,
    baseOutput: 20,
    outputName: 'Sel Kuasa NTE',
    desc: 'Nusantara Tech Element bagi menggerakkan dron dan radar pertahanan.',
    minDevLevel: 7,
  },
  'Loji Bauksit & Aluminium': {
    id: 'f_bauxite',
    name: 'Loji Bauksit & Aluminium',
    icon: '🧱',
    resourceId: 'BAUKSIT',
    category: 'Industri Berat',
    buildCostRM: 28000,
    baseOutput: 45,
    outputName: 'Bongkah Aluminium',
    desc: 'Kerangka badan pesawat tempur dan kubu pertahanan wilayah.',
    minDevLevel: 3,
  },
  'Ladang Cendana Hutan': {
    id: 'f_sandalwood',
    name: 'Ladang Cendana Hutan',
    icon: '🪵',
    resourceId: 'KAYU_CENDANA',
    category: 'Hasil Hutan Tropika',
    buildCostRM: 18000,
    baseOutput: 50,
    outputName: 'Kayu Balak Cendana',
    desc: 'Bahan binaan kapal layar perang tradisional dan eksport mewah.',
    minDevLevel: 2,
  },
  'Perladangan Kopi Pergunungan': {
    id: 'f_coffee',
    name: 'Perladangan Kopi Pergunungan',
    icon: '☕',
    resourceId: 'KOPI',
    category: 'Komoditi Minuman',
    buildCostRM: 15000,
    baseOutput: 70,
    outputName: 'Guni Biji Kopi',
    desc: 'Meningkatkan produktiviti rakyat dan memulihkan stamina pekerja.',
    minDevLevel: 1,
  },
  'Gedung Gandum & Makanan': {
    id: 'f_wheat',
    name: 'Gedung Gandum & Makanan',
    icon: '🌾',
    resourceId: 'GANDUM',
    category: 'Pertanian Makanan',
    buildCostRM: 12000,
    baseOutput: 80,
    outputName: 'Guni Gandum',
    desc: 'Bekalan makanan asas untuk mengekalkan populasi dan moral askar.',
    minDevLevel: 1,
  },
};